databases:
  - name: h_vaccine_db
    databaseName: h_vaccine_db
    user: django_user
    region: singapore
    plan: starter
 


services:
  - type: web
    name: h_vaccine
    env: python
    region: singapore
    plan: starter
    branch: master
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: h_vaccine_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
    